---
# tasks file for containerize-py-app
- name: Copying application
  copy:
    src:  "{{src_app_root}}"
    dest: "{{app_path}}/"

- name: Copying Dockerfile
  template:
    src:  "{{src_dockerfile}}"
    dest: "{{app_path}}/Dockerfile"

- name: Copying requirements
  copy:
    src:  "{{src_requirements}}"
    dest: "{{app_path}}/requirements.txt"

- name: Building docker
  command: "docker build -t {{app_image_name}} ."
  args:
    chdir: "{{app_path}}"
