FROM {{python_image}}
{% if app_maintainer|length > 0 %}
LABEL maintaner="{{app_maintainer}}"
{% endif %}

WORKDIR /app

COPY ./requirements.txt /app/

RUN pip install -r requirements.txt

COPY app /app/

{% for item in app_ports %}
EXPOSE {{item}}
{% endfor %}

ENTRYPOINT [ "{{python}}" ]
CMD [ "{{app_file}}" ]
